### ISSUE TITLE
Precipitation scaling

### ISSUE THREAD

**Issue by luisortizuriarte** [JStiles9552/Assignment_1_CLIM_680#2]
Precipitation is a field where linear color scales do not work well – You can specify specific levels for the contours (see the [matplotlib contourf documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contourf.html)). For precipitation, powers of two work well (e.g., 0.5, 1, 2, 4, 8, 16, 32 mm/day).

**Comment by luisortizuriarte** [comment]
For the scaling of your precipitation data, your chosen scale does not represent well the underlying precipitation. As a general rule, you want your scale to cover the range of values in your domain. In your figure, the values in the colormap are much higher than those in the actual map. 

Second, you might want to consider a non-linear normalization (see documentation here: https://matplotlib.org/stable/tutorials/colors/colormapnorms.html).

**Comment by JStiles9552** [comment]
I have revised the color scaling so that the scale covers the range of values and all colors are represented on the map
