### ISSUE TITLE
Precipitation units choice

### ISSUE THREAD

**Issue by luisortizuriarte** [JStiles9552/Assignment_1_CLIM_680#4]
Precipitation units of `meter `are not appropriate for plotting (a meter of rainfall is a VERY large amount!). Please convert your data to more appropriate unit like `millimeters`.

**Comment by pdirmeyer** [comment]
Units are still not right. You should recognize that the values seemed awfully low for mm/month - that was a clue that something was off.

See documentation [on the Copernicus website](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-monthly-means) under the variable "Total precipitation" - the data are actually daily accumulations expressed in meters, so multiplying by 1000 would result in mm/day, not mm/month. 

Also, when you make a change, please respond with your own comment in the issue describing what you have done to address the comment. This is part of documenting the evolution of your code.

**Comment by JStiles9552** [comment]
I have revised the maps so that the units now show mm/day
